// Text for the "i" buttons in the Logs and Health tabs. Keyed by the exact label shown in the
// UI, so cards/sections look up their own explanation (one place to edit wording).

export const LOGS_TAB_HELP: Record<string, string> = {
  live: 'Newest events from all apps. Refreshes every 10 seconds. Use it while reproducing a problem at a school.',
  all: 'Every diagnostic event uploaded by the apps (Windows, Android, Linux). Search, filter and sort; click a row for full details and the events just before it.',
  errors: 'Only ERROR, CRITICAL and FATAL events — things that went wrong.',
  crashes: 'Crash issues. Identical crashes are grouped into one issue by fingerprint, showing how many times, on how many schools and machines it happened.',
  exceptions: 'Exceptions and crash-type events reported by the apps, including handled exceptions.',
  performance: 'Slow operations, UI freezes, high memory/CPU and low disk warnings.',
  api: 'Network/API calls reported by the apps: failures, timeouts, retries and their durations.',
  user: 'What users did: screens opened, buttons clicked, forms submitted. Helps reproduce the steps before a failure.',
  system: 'App start/stop, login, database and file/asset events.',
  bugs: 'All grouped issues (crashes, errors, warnings, user “Report a Problem” submissions) with their lifecycle status.',
  dumps: 'Binary evidence (Windows minidumps, screenshots, log files) stored privately. Downloads use 60-second links and are audited.',
  diagnostics: 'Storage used by logs, automatic cleanup history, retention policy, Logs access roles and the security audit trail.',
};

export const HEALTH_TAB_HELP: Record<string, string> = {
  overview: 'One-screen status of every product: health score, incidents, devices, errors, crashes, infrastructure, and what changed recently.',
  schools: 'Per-school status: devices online/offline, errors and crashes today, versions installed. “Diagnostics →” opens that school’s logs.',
  devices: 'Every activated computer/tablet: heartbeat state, version, CPU/RAM/disk from the app, crashes and errors in the last 24 hours.',
  performance: 'How fast things are, as percentiles (P50 = typical, P95/P99 = slowest users). Plus per-endpoint API stats and per-module feature health.',
  incidents: 'Serious problems being worked on. Created automatically by CRITICAL rules or manually; move them through Detected → Investigating → … → Closed.',
  alerts: 'Rule-based warnings. Repeats of the same rule are grouped into one alert (no spam) and auto-resolve when the metric recovers.',
  infrastructure: 'Backend providers (Supabase, Vercel, Render, health checks), database internals and storage buckets. Values show their source and age.',
  cost: 'Monthly infrastructure cost. Providers don’t expose billing APIs, so amounts are entered manually and labelled as estimates.',
  deployments: 'Releases (web deploys + app versions seen in the field), version spread, update success, and “Potential Regression” warnings after a release.',
  settings: 'Connect providers (tokens stored encrypted, never shown again), define alert rules, and set heartbeat/retention thresholds.',
};

export const HELP: Record<string, string> = {
  // ── Health: cards / KPIs ──
  'Overall Health': '100 minus penalties for crash rate, error rate, API errors/latency, open incidents and alerts, providers down, and DB/storage near quota. Missing data never counts against the score.',
  'Active incidents': 'Incidents not yet Resolved/Closed. Each CRITICAL one lowers the health score by 15.',
  'Active users (15 min)': 'Distinct user IDs that sent telemetry in the last 15 minutes. Shows “Not available” if apps don’t report a user ID.',
  'Online devices': 'Devices whose last heartbeat is within the “online” window (Settings). Stale = slightly late; offline = beyond the stale window.',
  Products: 'Products whose 24-hour crash and error rates are within limits (crash ≤ 0.5%, errors ≤ 3% = healthy).',
  'API health (1 h)': 'Share of failed/timed-out API calls reported by the apps in the last hour, and the P95 latency (95% of calls were faster).',
  Database: 'Database size as a percentage of the plan quota you entered on the Supabase provider.',
  Infrastructure: 'Configured providers currently reporting healthy. Data comes from the backend sync job, not your browser.',
  'Errors (24 h)': 'Error-level events in the last 24 hours, and their share of all events. Click to open them in Logs.',
  'Crashes (24 h)': 'Crashes in the last 24 hours, crash rate per active device, and how many brand-new crash fingerprints appeared. Click to open in Logs.',
  'Schools online': 'Schools with at least one online device, plus app sessions started/ended today (IST).',
  'Device disk / RAM P95': '95th-percentile disk and RAM usage across devices (from the app heartbeat) — i.e. the fullest 5% of machines.',
  'Top crash issues': 'Open crash groups ordered by occurrences. Click a bug ID to investigate it in Logs.',
  'Health timeline': 'Deployments, incidents and alerts in time order — line them up to spot what changed right before a problem.',
  'Recent incidents': 'Latest incidents; manage them in the Incidents tab.',
  'Recent deployments': 'Latest web deployments and app versions first seen in the field.',
  'Latency percentiles (reported durations)': 'Timings the apps report (startup, slow operations, freezes, compile…). P50 = typical, P95/P99 = worst experiences.',
  'API endpoints': 'Per endpoint: request count, failures and latency percentiles, as reported by the apps.',
  'Feature health (from telemetry)': 'Per module: share of events that are errors. Crashes or > 10% errors = critical.',
  'Incident Center': 'Create incidents and move them through the workflow. Every change is recorded with your note and audited.',
  'Alert Center': 'Acknowledge = someone is looking. Resolve = closed manually (rules also auto-resolve when the metric recovers).',
  'Database (live from Postgres catalog)': 'Read directly from PostgreSQL statistics: size, growth, connections, cache hit, rollbacks, locks and slow queries.',
  'Storage buckets': 'Files and bytes per Supabase Storage bucket, uploads in the last 24 h and growth over 30 days.',
  'Cost entries': 'Month-to-date amounts per provider/category. Manual entries are labelled “Manual estimate”.',
  'Update health (7 days)': 'App update events reported by devices: success rate = installed ÷ (installed + failed).',
  'Releases & deployments': 'Web deployments (from Vercel/Render APIs) and app versions first seen on devices, with commit IDs.',
  'Infrastructure providers': 'Add the services you actually use. API tokens are encrypted at rest, used only by the backend, and never displayed again.',
  'Alert rules': 'IF a metric crosses a threshold FOR N minutes THEN raise an alert at that level, optionally opening an incident.',
  'Monitoring configuration': 'Heartbeat windows (online/stale/offline), API latency threshold and how long monitoring data is kept.',
  'Size': 'Current database size, and the percentage of your plan quota.',
  'Growth': 'Average monthly growth from daily size measurements, and the projected time until the quota is reached.',
  'Connections': 'Open database connections vs the server maximum.',
  'Cache hit': 'Share of reads served from memory (should be > 99%). Also deadlocks and queries waiting on locks.',
  'Rollbacks': 'Failed/rolled-back transactions vs committed ones since statistics were last reset.',
  'Long-running queries': 'Queries active for more than 30 seconds right now.',
  // ── Logs: drawer sections / cards / actions ──
  Occurrence: 'How often this grouped issue happened, where, on which versions/modules, and when it was first and last seen.',
  Behaviour: 'What should have happened vs what actually happened, as reported by the app.',
  Error: 'Exception type, message, codes and where in the code it was thrown.',
  Resolution: 'Root cause and fix recorded when the issue was resolved. Diagnostics are deleted after the grace period.',
  Application: 'Product, version, build number and git commit — maps the event to the exact release.',
  Deployment: 'Which school, installation and machine this came from (identified by the server, not the app).',
  Session: 'User/session/process at the time — use it to follow one session’s timeline.',
  Event: 'When and where in the app this happened.',
  System: 'Device OS, CPU, RAM, disk and display when the problem happened.',
  Network: 'Connectivity and request details at the time.',
  Performance: 'Memory/CPU state at the time.',
  'Application state': 'Uptime, current screen/module and other app state captured at the crash.',
  Evidence: 'Crash dumps / screenshots / logs. Downloads use short-lived links and are audited.',
  'Timeline (oldest → failure)': 'The events leading up to this failure, in order. Red = error, amber = warning.',
  'Diagnostic Storage': 'Space used by logs and evidence. Deleted rows are reused by Postgres automatically; the file may not shrink at once.',
  'Retention policy': 'How long each kind of diagnostic data is kept before automatic cleanup. Active investigations are never auto-deleted.',
  'Bulk cleanup': 'Permanently delete all resolved issues older than N days (Super Admin). Shows a preview first.',
  'Logs access (RBAC)': 'Who can use Logs and Health. Viewer: view · Developer: + download, infrastructure · Debug Admin: + resolve/delete/incidents · Super Admin: + settings, roles, audit.',
  'Security audit trail': 'Every view, download, delete and settings change in Logs/Health. Cannot be edited or deleted by users.',
  'Download Diagnostic Bundle': 'ZIP with crash records, stack traces, timelines, system info and a README. Marks the issue DOWNLOADED and is audited.',
  'Start investigating': 'Moves the issue to INVESTIGATING so the team knows someone owns it. It will not be auto-deleted.',
  'Mark as resolved': 'Record root cause, fix and fixed version. Raw diagnostics are then deleted after the configured grace period; a short summary is kept.',
  'Delete diagnostics': 'Permanently delete this issue’s raw logs, crashes and files now. Requires typing the bug ID.',
  'Event filters': 'Combine filters; all run on the server. Dates are in your local time. Click a column header to sort.',
};
