'use client';

import React, { useState, useTransition, useEffect } from 'react';
import { Edit2, Trash2, XCircle, CreditCard, School, AlertCircle, AlertTriangle, X } from 'lucide-react';
import GlassCard from '@/components/GlassCard';
import StatusBadge from '@/components/StatusBadge';
import { createPayment, updatePayment, deletePayment, cancelPayment } from './actions';
import { useToast } from '@/components/Toast';
import CustomSelect from '@/components/CustomSelect';

interface SchoolOption {
  id: string;
  name: string;
}

interface PaymentRow {
  id: string;
  schoolId?: string;
  vendorId?: string;
  parentId?: string;
  entityName: string;
  amount: number;
  keysCount: number;
  bankName: string;
  transactionId: string;
  paymentDate: string;
  status: 'Unpaid' | 'Pending Approval' | 'Paid';
}

interface PaymentsClientProps {
  initialPayments: PaymentRow[];
  schools: SchoolOption[];
  vendors: SchoolOption[];
  parents: SchoolOption[];
}

import { useSearchParams } from 'next/navigation';

export default function PaymentsClient({ initialPayments, schools, vendors, parents }: PaymentsClientProps) {
  const { toast } = useToast();
  const searchParams = useSearchParams();
  const [isPending, startTransition] = useTransition();
  const [filter, setFilter] = useState<'All' | 'Unpaid' | 'Paid'>('All');
  
  // Syncing payments with server dynamic revalidation
  const [payments, setPayments] = useState<PaymentRow[]>(initialPayments);
  useEffect(() => {
    setPayments(initialPayments);
  }, [initialPayments]);

  // Form State
  const [editingId, setEditingId] = useState<string | null>(null);
  const [entityType, setEntityType] = useState<'School' | 'Vendor' | 'Individual'>('School');
  const [selectedSchoolId, setSelectedSchoolId] = useState(searchParams.get('schoolId') || '');
  const [selectedVendorId, setSelectedVendorId] = useState('');
  const [selectedParentId, setSelectedParentId] = useState('');
  const [keysCount, setKeysCount] = useState('');
  const [paymentDate, setPaymentDate] = useState('');
  const [status, setStatus] = useState<'Unpaid' | 'Pending Approval' | 'Paid'>('Unpaid');

  // Retain for backing database updates when editing existing records
  const [amount, setAmount] = useState('');
  const [bankName, setBankName] = useState('');
  const [transactionId, setTransactionId] = useState('');

  // Confirmation Modal State
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [paymentToDelete, setPaymentToDelete] = useState<{ id: string; schoolName: string } | null>(null);

  const selectedSchool = schools.find(s => s.id === selectedSchoolId);

  const handleCancelForm = () => {
    setEditingId(null);
    setSelectedSchoolId('');
    setSelectedVendorId('');
    setSelectedParentId('');
    setKeysCount('');
    setPaymentDate('');
    setStatus('Unpaid');
    setAmount('');
    setBankName('');
    setTransactionId('');
  };

  const handleEdit = (payment: PaymentRow) => {
    setEditingId(payment.id);
    setEntityType(payment.schoolId ? 'School' : payment.vendorId ? 'Vendor' : payment.parentId ? 'Individual' : 'School');
    setSelectedSchoolId(payment.schoolId || '');
    setSelectedVendorId(payment.vendorId || '');
    setSelectedParentId(payment.parentId || '');
    setKeysCount(payment.keysCount.toString());
    
    setAmount(payment.amount.toString());
    setBankName(payment.bankName);
    setTransactionId(payment.transactionId);
    
    // Format date for <input type="date">
    const dateObj = new Date(payment.paymentDate);
    const yyyy = dateObj.getFullYear();
    const mm = String(dateObj.getMonth() + 1).padStart(2, '0');
    const dd = String(dateObj.getDate()).padStart(2, '0');
    setPaymentDate(`${yyyy}-${mm}-${dd}`);
    
    setStatus(payment.status);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (
      (entityType === 'School' && !selectedSchoolId) ||
      (entityType === 'Vendor' && !selectedVendorId) ||
      (entityType === 'Individual' && !selectedParentId) ||
      !keysCount || 
      !paymentDate
    ) {
      toast('Please fill in all the payment details.', 'error');
      return;
    }

    startTransition(async () => {
      try {
        const formData = {
          entityType,
          schoolId: selectedSchoolId,
          vendorId: selectedVendorId,
          parentId: selectedParentId,
          keysCount: parseInt(keysCount),
          paymentDate,
          status,
          // Forward existing values if editing, otherwise they will be defaulted/auto-generated by server action
          amount: amount ? parseFloat(amount) : undefined,
          bankName: bankName || undefined,
          transactionId: transactionId || undefined,
        };

        const res = editingId
          ? await updatePayment(editingId, formData)
          : await createPayment(formData);
        if (!res.ok) {
          toast(res.error, 'error');
          return;
        }
        toast(editingId ? 'Payment record updated successfully.' : 'Payment record added successfully.', 'success');
        handleCancelForm();
      } catch {
        toast('Something went wrong. Please try again.', 'error');
      }
    });
  };

  const confirmDelete = (id: string, entityName: string) => {
    setPaymentToDelete({ id, schoolName: entityName });
    setShowConfirmModal(true);
    toast(`⚠️ Warning: Deleting the payment record for "${entityName}" will permanently erase all connected activation key bindings!`, 'error');
  };

  const handleCancelPayment = (id: string, entityName: string) => {
    if (confirm(`Are you sure you want to revoke/cancel the payment status to "Unpaid" for ${entityName}?`)) {
      startTransition(async () => {
        const res = await cancelPayment(id);
        if (!res.ok) {
          toast(res.error, 'error');
          return;
        }
        toast('Payment status set to Unpaid.', 'success');
      });
    }
  };

  const filteredPayments = payments.filter(p => {
    if (filter === 'Paid') return p.status === 'Paid';
    if (filter === 'Unpaid') return p.status === 'Unpaid';
    return true;
  });

  return (
    <div className="space-y-8 max-w-6xl mx-auto relative">
      {/* Spacer to maintain layout height */}
      <div className="h-10"></div>

      {/* Header Panel & Acceptance Form */}
      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="flex justify-between items-center flex-wrap gap-4 border-b border-white/5 pb-6">
          <div>
            <h2 className="text-3xl font-extrabold text-white tracking-tight">
              {editingId ? 'Edit Payment Details' : 'Payment Details Acceptance'}
            </h2>
            <p className="text-xs text-zinc-400 mt-1">
              {editingId ? 'Modify registered payment details.' : 'Submit and log verified school payment transactions.'}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <button
              type="submit"
              disabled={isPending}
              className="px-5 py-2.5 bg-gradient-to-r from-accent-violet to-accent-blue text-xs font-semibold text-white rounded-xl shadow-[0_0_15px_rgba(139,92,246,0.25)] hover:shadow-[0_0_20px_rgba(139,92,246,0.4)] transition-transform active:scale-95 cursor-pointer disabled:opacity-55"
            >
              {isPending ? 'Saving...' : editingId ? 'Update Receipt' : 'Submit Receipt'}
            </button>
          </div>
        </div>

        {/* Entity Type Selection */}
        <div className="w-full md:w-1/3 mb-6">
          <label className="text-xs font-bold text-zinc-400 block mb-2">Entity Type</label>
          <CustomSelect
            required
            value={entityType}
            onChange={val => {
              setEntityType(val as any);
              // Reset specific selections when changing type
              setSelectedSchoolId('');
              setSelectedVendorId('');
              setSelectedParentId('');
            }}
            options={[
              { value: 'School', label: 'School' },
              { value: 'Vendor', label: 'Vendor' },
              { value: 'Individual', label: 'Normal Individual User' }
            ]}
            placeholder="Select Entity Type"
          />
        </div>

        {/* Form Inputs Grid */}
        <GlassCard className="/40 border border-white/5 p-6 space-y-6">
          <h3 className="text-xs font-bold text-zinc-300 uppercase tracking-widest flex items-center gap-2">
            <CreditCard className="w-4 h-4 text-accent-violet" />
            Payment info
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {entityType === 'School' && (
              <div className="space-y-2">
                <label className="text-xs font-bold text-zinc-400 block">Select Institution *</label>
                <CustomSelect
                  required
                  value={selectedSchoolId}
                  onChange={val => setSelectedSchoolId(val)}
                  options={schools.map(s => ({ value: s.id, label: s.name }))}
                  placeholder="Select School"
                />
              </div>
            )}
            
            {entityType === 'Vendor' && (
              <div className="space-y-2">
                <label className="text-xs font-bold text-zinc-400 block">Select Vendor *</label>
                <CustomSelect
                  required
                  value={selectedVendorId}
                  onChange={val => setSelectedVendorId(val)}
                  options={vendors.map(v => ({ value: v.id, label: v.name }))}
                  placeholder="Select Vendor"
                />
              </div>
            )}

            {entityType === 'Individual' && (
              <div className="space-y-2">
                <label className="text-xs font-bold text-zinc-400 block">Select Individual *</label>
                <CustomSelect
                  required
                  value={selectedParentId}
                  onChange={val => setSelectedParentId(val)}
                  options={parents.map(p => ({ value: p.id, label: p.name }))}
                  placeholder="Select Individual"
                />
              </div>
            )}

            <div className="space-y-2">
              <label className="text-xs font-bold text-zinc-400 block">Keys Issued Count *</label>
              <input
                type="number"
                required
                placeholder="e.g. 5"
                value={keysCount}
                onChange={e => setKeysCount(e.target.value)}
                className="w-full px-4 py-3 bg-white/5 border border-white/10 hover:border-white/15 focus:border-accent-violet rounded-xl text-sm text-white placeholder-zinc-500 focus:outline-none transition-all"
              />
            </div>

            <div className="space-y-2">
              <label className="text-xs font-bold text-zinc-400 block">Payment Date *</label>
              <input
                type="date"
                required
                value={paymentDate}
                onChange={e => setPaymentDate(e.target.value)}
                onClick={e => {
                  try {
                    (e.target as any).showPicker();
                  } catch {}
                }}
                style={{ colorScheme: 'dark' }}
                className="w-full px-4 py-3 bg-[#121216] border border-white/10 hover:border-white/15 focus:border-accent-violet rounded-xl text-sm text-zinc-300 focus:outline-none transition-all cursor-pointer"
              />
            </div>

            <div className="space-y-2">
              <label className="text-xs font-bold text-zinc-400 block">Audit Clearance Status *</label>
              <CustomSelect
                required
                value={status}
                onChange={val => setStatus(val as any)}
                options={[
                  { value: 'Unpaid', label: 'Unpaid (Draft / Flagged)' },
                  { value: 'Pending Approval', label: 'Pending Approval (Awaiting Clearance)' },
                  { value: 'Paid', label: 'Paid (Verified & Approved)' }
                ]}
                placeholder="Select Status"
              />
            </div>
          </div>
        </GlassCard>
      </form>

      {/* Horizontal Filter */}
      <div className="flex items-center gap-3">
        {(['All', 'Unpaid', 'Paid'] as const).map(f => (
          <button
            key={f}
            type="button"
            onClick={() => setFilter(f)}
            className={`px-5 py-2 rounded-full text-xs font-bold transition-all border cursor-pointer ${
              filter === f
                ? 'bg-accent-violet/10 text-accent-violet border-accent-violet/30'
                : 'bg-white/5 text-zinc-400 border-transparent hover:bg-white/10 hover:text-zinc-200'
            }`}
          >
            {f}
          </button>
        ))}
      </div>

      {/* Payment Table Records */}
      <GlassCard className="/40 border border-white/5 overflow-hidden p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-white/10 bg-white/[0.02]">
                <th className="py-4 px-6 text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Transaction ID</th>
                <th className="py-4 px-6 text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Entity Name</th>
                <th className="py-4 px-6 text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Date</th>
                <th className="py-4 px-6 text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Status</th>
                <th className="py-4 px-6 text-[10px] font-bold text-zinc-500 uppercase tracking-widest text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {filteredPayments.length > 0 ? (
                filteredPayments.map(payment => (
                  <tr key={payment.id} className="hover:bg-white/[0.02] transition-colors group">
                    <td className="py-4 px-6">
                      <span className="text-sm font-medium text-white">{payment.transactionId}</span>
                    </td>
                    <td className="py-4 px-6">
                      <span className="text-sm text-zinc-300">{payment.entityName}</span>
                    </td>
                    <td className="py-4 px-6">
                      <span className="text-sm text-zinc-400">
                        {payment.paymentDate ? (() => {
                          const date = new Date(payment.paymentDate);
                          const day = String(date.getDate()).padStart(2, '0');
                          const month = String(date.getMonth() + 1).padStart(2, '0');
                          const year = date.getFullYear();
                          return `${day}/${month}/${year}`;
                        })() : 'N/A'}
                      </span>
                    </td>
                    <td className="py-4 px-6">
                      <StatusBadge status={payment.status === 'Paid' ? 'SUCCESS' : payment.status === 'Unpaid' ? 'Unpaid' : 'Pending'} />
                    </td>
                    <td className="py-4 px-6 text-right">
                      <div className="flex items-center justify-end gap-2 opacity-50 group-hover:opacity-100 transition-opacity">
                        <button
                          type="button"
                          onClick={() => handleEdit(payment)}
                          className="p-2 hover:bg-white/10 rounded-lg text-zinc-400 hover:text-accent-violet transition-colors cursor-pointer"
                          title="Edit"
                        >
                          <Edit2 className="w-4 h-4" />
                        </button>
                        <button
                          type="button"
                          onClick={() => confirmDelete(payment.id, payment.entityName)}
                          className="p-2 hover:bg-white/10 rounded-lg text-zinc-400 hover:text-red-400 transition-colors cursor-pointer"
                          title="Delete"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={5} className="py-12 text-center text-zinc-500 text-sm">
                    <AlertCircle className="w-5 h-5 mx-auto mb-2 text-zinc-600" />
                    No payments found matching criteria.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </GlassCard>

      {/* Confirmation Modal */}
      {showConfirmModal && paymentToDelete && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
          <GlassCard className="w-full max-w-md border border-white/10 p-6 space-y-6 shadow-2xl relative">
            <button 
              onClick={() => {
                setShowConfirmModal(false);
                setPaymentToDelete(null);
              }}
              className="absolute top-4 right-4 text-zinc-400 hover:text-white transition-colors cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>

            <div className="flex items-start gap-4">
              <div className="p-3 bg-rose-500/10 border border-rose-500/20 text-rose-400 rounded-2xl">
                <AlertTriangle className="w-6 h-6" />
              </div>
              <div className="space-y-2">
                <h3 className="text-lg font-bold text-white">Confirm Payment Deletion</h3>
                <p className="text-xs text-zinc-400 leading-relaxed">
                  Are you absolutely sure you want to delete the payment record for <strong className="text-zinc-200">{paymentToDelete.schoolName}</strong>?
                </p>
                <div className="p-3 bg-rose-500/5 border border-rose-500/10 rounded-xl mt-2">
                  <p className="text-[10px] text-rose-400 font-semibold leading-relaxed">
                    ⚠️ CRITICAL NOTE: All associated cryptographic activation keys linked to this receipt will be permanently deleted from the database.
                  </p>
                </div>
              </div>
            </div>

            <div className="flex justify-end gap-3 pt-2">
              <button
                onClick={() => {
                  setShowConfirmModal(false);
                  setPaymentToDelete(null);
                }}
                disabled={isPending}
                className="px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-semibold text-zinc-300 rounded-xl transition-all cursor-pointer disabled:opacity-55"
              >
                Cancel
              </button>
              <button
                onClick={() => {
                  startTransition(async () => {
                    const res = await deletePayment(paymentToDelete.id);
                    if (!res.ok) {
                      toast(res.error, 'error');
                      return;
                    }
                    toast('Payment record deleted successfully.', 'success');
                    setShowConfirmModal(false);
                    setPaymentToDelete(null);
                  });
                }}
                disabled={isPending}
                className="px-4 py-2 bg-gradient-to-r from-rose-600 to-red-500 hover:from-rose-500 hover:to-red-400 text-xs font-semibold text-white rounded-xl shadow-[0_0_15px_rgba(239,68,68,0.25)] transition-all cursor-pointer disabled:opacity-55"
              >
                {isPending ? 'Deleting...' : 'Confirm Delete'}
              </button>
            </div>
          </GlassCard>
        </div>
      )}
    </div>
  );
}
